### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by isalazar4826** [meraki/spark-operations-bot#16]
hello 

when deploy the bot in heroku ,  in the logs show the Error HTTP 500

2019-06-17T20:11:55.022871+00:00 app[web.1]: Message from: mario_salazar@connext.com.mx
2019-06-17T20:11:55.022958+00:00 app[web.1]: Found command: meraki-health

**2019-06-17T20:12:12.919962+00:00 app[web.1]: [2019-06-17 20:12:12,913] ERROR in app: Exception on / [POST]**

2019-06-17T20:12:12.919975+00:00 app[web.1]: Traceback (most recent call last):
2019-06-17T20:12:12.919978+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2019-06-17T20:12:12.919980+00:00 app[web.1]:     response = self.full_dispatch_request()
2019-06-17T20:12:12.919982+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2019-06-17T20:12:12.919984+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2019-06-17T20:12:12.919987+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2019-06-17T20:12:12.919989+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2019-06-17T20:12:12.919991+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2019-06-17T20:12:12.919993+00:00 app[web.1]:     raise value
2019-06-17T20:12:12.919996+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2019-06-17T20:12:12.919998+00:00 app[web.1]:     rv = self.dispatch_request()
2019-06-17T20:12:12.920000+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2019-06-17T20:12:12.920002+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2019-06-17T20:12:12.920007+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ciscosparkbot/Spark.py", line 266, in process_incoming_message
2019-06-17T20:12:12.920009+00:00 app[web.1]:     reply = self.commands[command]["callback"](message)
2019-06-17T20:12:12.920011+00:00 app[web.1]:   File "/app/cico_meraki.py", line 603, in get_meraki_health_html
2019-06-17T20:12:12.920014+00:00 app[web.1]:     return get_meraki_health(incoming_msg, "html")
2019-06-17T20:12:12.920016+00:00 app[web.1]:   File "/app/cico_meraki.py", line 458, in get_meraki_health
2019-06-17T20:12:12.920018+00:00 app[web.1]:     newnetlist = do_split_networks(netlistup)
2019-06-17T20:12:12.920020+00:00 app[web.1]:   File "/app/cico_meraki.py", line 425, in do_split_networks
2019-06-17T20:12:12.920022+00:00 app[web.1]:     thisupl = {"uplinks": in_netlist[net]["devices"][dev["serial"]]["uplinks"]}
**2019-06-17T20:12:12.920789+00:00 app[web.1]: KeyError: 'Q2FV-4QSY-KBF6'**

**2019-06-17T20:12:12.921873+00:00 app[web.1]: 10.31.50.114 - - [17/Jun/2019 20:12:12] "POST / HTTP/1.1" 500 -**

2019-06-17T20:12:12.926966+00:00 heroku[router]: at=info method=POST path="/" host=merakiivantest.herokuapp.com request_id=83ccaaf6-8698-4f35-b58a-3365475d2392 fwd="18.217.166.80" dyno=web.1 connect=0ms service=18628ms status=500 bytes=450 protocol=https

**Comment by joshand** [comment]
Confirmed. Working on a fix now.

**Comment by joshand** [comment]
@isalazar4826 - please re-deploy and test again; let me know if it's still not working!

**Comment by isalazar4826** [comment]
ok, let mi try

**Comment by isalazar4826** [comment]
It is working , i get the info of meraki  dashboard

**Comment by joshand** [comment]
Thank you. Closing issue.
